### PR TITLE
Fix changing belt direction

### PR DESCRIPTION
**Pull request by mibac138**

### CODE REVIEW

**Comment by Eldrinn-Elantey** [comment]
I made these changes to the mod locally at home and found that now drones are being updated (replacing one type of pipeline with another (green update plan)) randomly change the direction. It is impossible to return it automatically and you have to manually restore the line

**Comment by Tubbles** [comment]
Please add more information, what is this PR supposed to achieve? Is this a bug fix?

**Comment by mibac138** [comment]
As far as I remember I had an issue when rotating a placed belt using construction drones. The scenario went something like this:
1. place a belt
2. shift-place a rotated belt (create a ghost) on the same tile
3. the drone goes to place the belt but it's exactly the same as it was (but it should've been rotated)

After running the game with this PR, the issue was fixed

**Comment by Tubbles** [comment]
Ok I can reproduce that issue, although I am not quite sure what you are referring to @Eldrinn-Elantey, I am not seeing any problems when using the upgrade planner

**Pull request merged**
