### PR TITLE
quick and dirty update for factorio 2.0

### PR DESCRIPTION
**Pull request by Dumdidldum**
Hi,
i love this mod!
Therefore i updated it to 2.0

Disclaimer!
This is my first time modding factorio so i just fixed the code until the game did no longer complain.
It is working so far in regular play.

What i did not understand really was the way "collisions" work, so there are probably some changes needed.

### CODE REVIEW

**Comment by Tubbles** [comment]
Hey, thank you again for your contribution! After a quick smoke test I am ready to merge this. I think the next step would be to push this out on the mod portal and see what happens :) Of course with a fat warning sign that 2.0 support is experimental

**Comment by oReazy** [comment]
Error while running event Updated_Construction_Drones::on_ai_command_completed (ID 128)
real number expected got inf.
stack traceback:
	[C]: in function '__newindex'
	...ated_Construction_Drones__/script/construction_drone.lua:1964: in function <...ated_Construction_Drones__/script/construction_drone.lua:1956>
	(...tail calls...)
	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>

@Dumdidldum @Tubbles

**Comment by oReazy** [comment]
image

**Comment by oReazy** [comment]
image
Another mod breaks down because of this, most likely at this moment the UCD crash happened

**Comment by Dumdidldum** [comment]
hi, i will try to take a look at these things soon

**Comment by oReazy** [comment]
> Error while running event Updated_Construction_Drones::on_ai_command_completed (ID 128) real number expected got inf. stack traceback: [C]: in function '**newindex' ...ated_Construction_Drones**/script/construction_drone.lua:1964: in function <...ated_Construction_Drones__/script/construction_drone.lua:1956> (...tail calls...) **core**/lualib/event_handler.lua:47: in function <**core**/lualib/event_handler.lua:45>
> 
> @Dumdidldum @Tubbles

Error while running event Updated_Construction_Drones::on_ai_command_completed (ID 128)
real number expected got inf.
stack traceback:
	[C]: in function '__newindex'
	...ated_Construction_Drones__/script/construction_drone.lua:1964: in function <...ated_Construction_Drones__/script/construction_drone.lua:1956>
	(...tail calls...)
	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>
	
**The error appeared. Opened the card**

**Comment by Tubbles** [comment]
@oReazy Thank you for the reports. To aid in bug hunting, please attach the following:

* [factorio-current.log](https://wiki.factorio.com/Log_file)
* A general description of how the bug happened
* Any error messages
* If possible, consider uploading a save file where the bug is reproducible

**Comment by oReazy** [comment]
[factorio-current.log](https://github.com/user-attachments/files/17529481/factorio-current.log)
Mistakes accumulate like a snowball. The error crashes on average after 30-40 minutes of play. You open some kind of window, for example a map, and BOOM! Departure. This can be repeated if you just play for a while.

Maybe the mod has incompatible mods?

**Comment by oReazy** [comment]
I found a bug that occurs

**Comment by oReazy** [comment]
[_autosave2.zip](https://github.com/user-attachments/files/17529666/_autosave2.zip)

Steps:
1. Copying the blueprint
`0eNq1netuG0cShd+Fv6lg+jrdfhXDCGSHmxCQaa0kbzYI/O7LobyJLPEsT3+c/RN4xs7h6ct0VVedrv5z8/Hu6+7+YX942rz7c7P/9OXwuHn3/s/N4/7Xw+3d8u5w+3m3ebd5erg9PN5/eXi6+bi7e9p82272h192/968C9+2Z/757ePj7vPHu/3h15vPt59+2x92N+HF/xS/fdhudoen/dN+9/yDp4c/fj58/fxx93BE3Yof3m7uvzwe/7cvh+XXlt+fw09lu/nj+Kep/FS+LXRegcUBsHgJLA2ApUtg+S+wx8+3d3c3u7vdp6eH/aeb+y93u3OI5RJiGaCXL4HVV/Tubj/fnwNql4Dm0Xb2S4jNo9amS0Dd77D243huN7/sH47tOP2LdgY6TAPYcRA7mB1wccaEaCLNF5HS4DC3ehEy+13YLy4EYeDr6BdXglAH0C4uBWEeQLv45YaGFtAq0DpCm8VyPKH1WHCLAS3ICo3ZCtVSZiwUWkZru2opsxSK28C3MNcf0C4udfHvL+Mft49PN/vD4+7h6fg3Z6BnDZ3PQf/9mZz1WP6nZXr+hSP+/n4B2D98Odz8urt9uPn9t93ubvPfv/r5n19v744/evwnhy8Px3Vxc45It9vYwlgb04QsXHWGJgVk4TzsiHhbUyolxNvDzv5QZg0d4jnsMjpfW/2/zNc08L23PtiB/vfe2mgHNuRPiDU0dYQm1tA8Ie9EcMsBeScKLSI01dKEWqrQMvKcVEsLQlPcKvKcukCbEVoTaA35OopbR2iCW5mQ5yS4FeYjKm4ReU4KLSE01dKM/LDurMulIOxmYVdk7D3sGWF7fdKQI+Fhd4Rt9UmdkP22eNeAsD3eEVlc8e3VhNDEt1czspEKrSA01dKKLK7iNiM0xa0hi6u4dYQmuM0TsbghCDQU1g6TQEOxCsktITTFLROLK7kVhKa4VWJxJdqM0FRLG7GxJ7SLa+fcEfbkYLcJxGjeQp+LX7TAYzTff2GdPW+LIEZjtjERF8UcmoywrSnVCnFRTOyKsL0+mUGM5i302RBDazxGs+587cQP8wanI//RG5weQPzHHJyO/Ee19nfkP6q1v2fiVUk05D9KNJTrkv2G/EeJhvxH2VLkPypuYWIOZFJwzIOMCo65kJIdyndpuIzYycYyL1LCjbiR5Qe4y+tUmJhbKckyv1KODHMlzba/0E2YuhPZ7jcyCV95ojHjqPZEQzG/L3oKEeb4JQ+ceX4mOHP9zG6ZR5UzevjaqHRGQ3WsnZGYkTlp0dmxhIiifHJFGRFe9GmUK/PTZL+iQJ+GY56a7EkU6tNwzFeTjWXOmmTHvDXFLjFvTerhmLeWFRzz1iQci/jJxrKQn4Rj3ppsLBIoabgZwcnGNhI+y9bi90KkMB4/yyvGI0KeSADNa+WI3KElDX7WZchIihQ8IW9GWiQXPCNws1sKiaJlbxPwQjkxHkZbd9rOyNNRS8eI7OIFnBRIdxItMwdhRIbRL6/pBWmSZE+OCDH6ZQNWkCpJs0OyJM0O6ZI0OyRMCrOCQ8qkoPTmBUmTNBzSJsnGViRO0nBInSQbOyKReOGaSLiE4GRjM/F0LKFzqOUKT2dNdWx4IbcY8HTMViI5U7Ckt2FEi9F+nIsGOBI0mcxndNjKZD4H4ul4kuTwQscx7umsOm1HNCAvXBO1dIyIQFq/uHTMhXg67iCwBJfkOiM42ZMNuSaSXUdwil2bkGui2LWA4CS7iFyTruASgmsKjuW4JFxBcLKxFbkmEm5GcLKxLKkl4fpw2kk1tE887SQxw3DaSUKxeIal/g2dxTNMcBbPaB54Qd1igtfhtJMcvnk47SShGk87SUymO2rqtDCLQXQFx2IQkh2LQUh2LAYh2bEYhGTHYhCSHYpBxKDgUAwiTgoOxSA0HIpByMYGFIPQcCgGIRsbItjlx2Ad2Q4oIBEtWWN8oZkYDiF8/4mVDoSHAkIIbhcifUWcvC6cEbg5Pig+4TJHtWBM5nECIYS32Gd3rzEGHkJYd9qO6DhaH+3DBCIAdh8iVYdcUZmqQ66oTNWh2SFVh2aHVB2aHVJ1SHZM1RGTgkOqjhgVHFJ1aDik6tCNRaoODYdUHbqxSNURLaFgZBqPmDxwdHDYZY4C7SbzjOrJmMyZjMNlzmyTyRzFzl3mzDaprzAz26S+wsxsk2THbJNkx2yTZMdsk2JXmG1SlS4Ls01ZwTHbJOGYbZKNZbZJwjHbJBtbyR7YUrvFwkyTpRmLBYXVY/bAr1AjxjVlXbESNaI5PhXVRTO7cETg0eLg4Fd0IsUFRydS3G4hasToCeFivUKNuPK0RWpEd4CQNtEdIKJUdAdoRlkCaQtmlCWQtmBGWQLNDmUJNDuUJdDsUJZAs2NZAlWodGZZAlVFdWZZAsmOZQkUu8ayBBIukEOpsXqf8JBQowyjs7SBGqiGCq3ZZMuoFEGPWcVSBI05j0oRNBSLg3iFgxuLg1iawNhZHMRj3lkcxGQeR6UIcvg6L/muMfOovEFDFeTPqI++o6q3b0fl7J5hqCjGNAqO6t664B05S6KXExN8qDmQhgQf8TJcRN6NbGxCcJJdRt5NV3AFwTUFV5F3I9nNCE6yI4cwY/NqsKOCGZLqkPqjXuzIcEWJte8dsFJZ8UBqrJljEJAwMTavED4LbZjgqNhG7B44Kr3rgpNCa2975Xwt93BFpbWVpy2SPMrvcUQr0kZ7jRXukEtRRJXhddMTgpPsWGhDsmOhDckOhTZSUHAotJEmBYdCG5odCm1IdolUHE2WPi4NKTzqZaroRKbsyBcKj2FrndYUe6WRq07C6Bggm5cm7/oXZPNccCSATMEDRwJIF7wDa508fV16oRsZttbrTtuMLKD8HnME1truNSQrkUsRE5LopiMhiWZXiXnV7NCVepodulMvJQWHLtVLQkiSCrpVT7IbEpLEy+yYCZRwaTQ+rhuacXxcY5bR+LiGQlL9ZGnWErsZxQVHkf2UPHAk1TfB6zQaH5fDVwOOj2vM4QtbNRSzLuqzZDegaHbMukh2zLpIdsy6SHbMuqhbqiuzLiIJn2ZmXRS7mVkXyY4cN0vF2ofMKG+cinfT4RXHzb7/xEo+8UyOm7ldyGxY9rqQ2TATnNkwc/CZDfPAGzlu9hZbXKJ5xXGzdadtQ3svt5nMOpoDxGylWlEbs5VqRW3MVkp2zFZKdsxWqhxsY7ZSXgrLbKVi15mtlOzYTsy7ubczY+ndB91Ris1lzsKNJjgLN5rdwsKNJjgSBLvdgrJmHvPMVCRJ3s2MBMHqK8xMRaLZIRWJZodUJEndDMxUJEldW8xUJJodUpFodkRFkiwFQ2YqkmSl6jPTlKTmgV+hMElrpuozUpiY48Ouc3HHB5W+csFR6St38Nn+zwQnCpPkaSXyNQqTlactOTzjNpNdFGNOLaY3MUefqU+kLWDqE2kLmPpEs0PqE80OqU9yUHBIfZInBdfI0ZU8mTMeiVEk2aEKI3mU7JAcpQyjow2hjY52hHKSpTya+NNjVnDiT2PW0cSfhkJxzWwJPTKrPuKCo7hmtsQ1OaMy3y54GE38yeHLw0k6DcXP2GhMVJo7W5dZ54xO3chvfkgVMo1yncnBGBccle12wdGpGzkjCiriLQetoCLemh0q4p2TgkNFvHNUcORSi2zdXZiHqpLUyy1HFbN0y2e+r//eASttkEoD+3p3DJhFs9QmuTKLZoKjc6Q5euCoEIkLnsC+Pns3DOea+b5+3WlbyaUWdjPReVW5drDSI3LtqKgwl2aHCnNJdjMqzJWLgkOFuXJWcETxki25RmaKF00VVUrQHXnFJU95Te1BnsklT+4YsN2fJT3IMzpDkLMHjmoumOCN2UqvWxq55Cl7WpLcrrjkad1p20gRZbuZbF+pPvbGdpJqKWKqFs0OqVo0O6RqySonzFQtWeWEO0oPargwHMhTDX1TzmQgkCcx03AgT0Ih2Ur2VA7sypo8e+Aob+cyR7IVl3kbDuTJ4es8+iYwyzQNBwclFMquqc+yMF2KZod0KZod0qXkruCQLiU3BUcKvubu+INlQgVfs5WhLVO7wqXuK/omZerEpfa6MKB6XdnKQ5fA4ize+AQWZzGZo6ooLvNMXOpu+ZollCtc6lWnbajEpXabyaIu5gCxGIxaUQOLwagVNaIYTAkKDsVgyqTgUOK8WEnUElEQpkweOHJJXebIJXWZI5fUZY5cUpc5UlK7zJGS2mSeUGZQfjYJZQblR51QZrAkBYcygyUqOJIZLFZWqiSUGSzJG3SUJyzRA78ia1jWTL+URLKG7vigrKE5PkwH44Kj6wvMwc/o8mEXnGQNi5dOK/mKrOG60zaTrKHdTJQ1dKcW8mbd0UferFy82VU/0rSwq35KVnDoXGDx7lMoQ4KbNIyeiF7WRs9EL2ujM7Nb1DAyQ+uSnUfD7Hq+NRxm15h9NMwuoSoK7xQrNVjYfT4uODOI2QNH4R0XPI+G2fXwFRxm15h1NMyuoZjZUh89u2enWJdPlSEhTBgEH7pnZxoFR4dsXXB0B48LjhIdcrrNaNtYParMfqkUz8zsl0rxzNdsDeuaPvaMtobmGCCRTLGSn6UxS2iCo0RHqR44SnS44Ghr6F3YU9o1W8NVp21DW0O3mWxrqNaOxqyqWjsaOXpfvOxhQ0fvi0qUMDVNUYmSfsXx+rJqKqyT4/XmGHR0vL54mbCOjte74Cwn4mVwmUzHBSfH64uZ2uxXHK9fedqS4/VmM+uEjtertaMyyY9aO+qE0ph1UnDDpXlrUFC8NK/GHC7Nq6HQd1etjF6dkAC8Th44Ov7rgqO0h9ktYbg0rxy+wEvzaszhU78aChUffP4sP2w3vx878nHz7v37vC3beVs+bN8f/7s9ov71x2MHLH9eXh0f+vPD8vL109FZeX7qp6f2/LS8ffW0XDb5/NSWp/78Y6e3r56Wstunp+XtdimTvDyd3r56Ws7pn56Wt9vlMPTydHr7+unoe5yelrfbRbh5elrevnpaYpnPT0uLltjT8nR6++ppWYNOT8vbbf3eZae335+Ofb1/2n0+DtPHu6+7+4f9YRmhf+0eHk8DVGrsx58peZprndO3b/8BTwyySg==`
2. We put them on trees with the demolition of trees that interfere
image
3. We select all trees for demolition (demolition plan current tree)
image
4. Error
image

**Comment by oReazy** [comment]
@Tubbles @Dumdidldum

**Comment by oReazy** [comment]
https://youtu.be/VOrqiRaUBKc

**Pull request merged**
